sudo: required

language: node_js

services:
- docker

install:
- docker build -t webchat.azurecr.io/samples-preserve-history .

script:
- echo

deploy:
  provider: script
  script: bash scripts/docker_push
  on:
    branch: master
